### ISSUE TITLE
rocko compatibility

### ISSUE THREAD

**Issue by ryancausey** [pauldotknopf/meta-intel-media-stack#3]
Is this specifically only compatible with sumo? We're trying to use this with rocko and ran into the compatibility error when updating to the latest version of this repository.

**Comment by pauldotknopf** [comment]
It was working initially with rocko. I have since moved to sumo, but I don't remember changing anything that would have broke rocko.

What errors are you getting?

**Comment by ryancausey** [comment]
The error is the incompatible layer error due to LAYERSERIES_COMPAT_meta-intel-media-stack only containing "sumo" instead of "sumo rocko". If I update the compatibility to "sumo rocko" it seems to work fine. I was just probing for if there was a specific reason this was limited to compatibility with sumo.

`ERROR: Layer meta-intel-media-stack is not compatible with the core layer which only supports these series: rocko (layer is compatible with sumo)`

**Comment by pauldotknopf** [comment]
Ah, yeah, sorry.

I update to sumo and got that warning during build, so I threw it in not thinking about rocko.

**Comment by ryancausey** [comment]
I can make a PR if you want.

**Comment by pauldotknopf** [comment]
Pretty please.

**Comment by ryancausey** [comment]
Closing now that the PR is merged.
